// Anthony J. Clark. Copyright (C) 2015. Apache License 2.0.
#ifndef HEADER_SRC_INFO_H_INCLUDED
#define HEADER_SRC_INFO_H_INCLUDED

/*
 * AUTO-GENERATION WARNING:
 *     This file has been automatically generated from "info.h.in.cmake".
 *     DO NOT edit this file, as any changes will be automatically discarded.
 */

#define APPLICATION_NAME               "raptorlang"
#define APPLICATION_CODENAME           "raptor"
#define APPLICATION_COPYRIGHT_YEARS    "2015"
/* #undef APPLICATION_VERSION_MAJOR */
#define APPLICATION_VERSION_MINOR      "1"
/* #undef APPLICATION_VERSION_PATCH */
#define APPLICATION_VERSION_TYPE       "SNAPSHOT"
#define APPLICATION_VERSION_STRING     "0.1.0-SNAPSHOT"
#define APPLICATION_VENDOR_ID          "com.AJC"
#define APPLICATION_VENDOR_NAME        "AJC"
#define APPLICATION_VENDOR_URL         "https://github.com/anthony-jclark/raptorlang"
#define APPLICATION_ID                 "com.AJC"

#ifndef APPLICATION_NAME
#   error "Please specify the application name in the top-level CMakeLists.txt file."
#endif

#ifndef APPLICATION_CODENAME
#   error "Please specify the application codename in the top-level CMakeLists.txt file."
#endif

#ifndef APPLICATION_COPYRIGHT_YEARS
#   error "Please specify the application copyright years (years during which this application was created, edited, or modified) in the top-level CMakeLists.txt file."
#endif

#ifndef APPLICATION_VERSION_MAJOR
#   define APPLICATION_VERSION_MAJOR "0"
#endif

#ifndef APPLICATION_VERSION_MINOR
#   define APPLICATION_VERSION_MINOR "0"
#endif

#ifndef APPLICATION_VERSION_PATCH
#   define APPLICATION_VERSION_PATCH "0"
#endif

#ifndef APPLICATION_VERSION_TYPE
#   define APPLICATION_VERSION_TYPE "SNAPSHOT"
#endif

#ifndef APPLICATION_VERSION_STRING
#   define APPLICATION_VERSION_STRING APPLICATION_VERSION_MAJOR "." APPLICATION_VERSION_MINOR "." APPLICATION_VERSION_PATCH "-" APPLICATION_VERSION_TYPE
#endif

#ifndef APPLICATION_VENDOR_ID
#   error "Please specify the application vendor id in the top-level CMakeLists.txt file."
#endif

#ifndef APPLICATION_VENDOR_NAME
#   error "Please specify the application vendor name in the top-level CMakeLists.txt file."
#endif

#ifndef APPLICATION_VENDOR_URL
#   error "Please specify the application vendor URL in the top-level CMakeLists.txt file."
#endif

#ifndef APPLICATION_ID
#   define APPLICATION_ID APPLICATION_VENDOR_ID "." APPLICATION_CODENAME
#endif


#ifndef VERSION_MESSAGE
#   define VERSION_MESSAGE APPLICATION_NAME " v" APPLICATION_VERSION_STRING "\n" APPLICATION_VENDOR_NAME "; Copyright (C) " APPLICATION_COPYRIGHT_YEARS
#endif

#ifndef VERSION_TRIPLET_MESSAGE
#   define VERSION_TRIPLET_MESSAGE APPLICATION_VERSION_STRING
#endif

#ifndef APPLICATION_IDENTIFIER
#   define APPLICATION_IDENTIFIER APPLICATION_ID
#endif

#endif




